// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v5.26.1
// source: rpc_get_membership_by_barcode.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMembershipByBarcodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Barcode string `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
}

func (x *GetMembershipByBarcodeRequest) Reset() {
	*x = GetMembershipByBarcodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_membership_by_barcode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembershipByBarcodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipByBarcodeRequest) ProtoMessage() {}

func (x *GetMembershipByBarcodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_membership_by_barcode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipByBarcodeRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipByBarcodeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_membership_by_barcode_proto_rawDescGZIP(), []int{0}
}

func (x *GetMembershipByBarcodeRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type GetMembershipByBarcodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId      string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CurrentTier     string `protobuf:"bytes,3,opt,name=current_tier,json=currentTier,proto3" json:"current_tier,omitempty"`
	AvailablePoints int32  `protobuf:"varint,4,opt,name=available_points,json=availablePoints,proto3" json:"available_points,omitempty"`
	TotalPoints     int32  `protobuf:"varint,5,opt,name=total_points,json=totalPoints,proto3" json:"total_points,omitempty"`
}

func (x *GetMembershipByBarcodeResponse) Reset() {
	*x = GetMembershipByBarcodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_membership_by_barcode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMembershipByBarcodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipByBarcodeResponse) ProtoMessage() {}

func (x *GetMembershipByBarcodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_membership_by_barcode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipByBarcodeResponse.ProtoReflect.Descriptor instead.
func (*GetMembershipByBarcodeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_membership_by_barcode_proto_rawDescGZIP(), []int{1}
}

func (x *GetMembershipByBarcodeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMembershipByBarcodeResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetMembershipByBarcodeResponse) GetCurrentTier() string {
	if x != nil {
		return x.CurrentTier
	}
	return ""
}

func (x *GetMembershipByBarcodeResponse) GetAvailablePoints() int32 {
	if x != nil {
		return x.AvailablePoints
	}
	return 0
}

func (x *GetMembershipByBarcodeResponse) GetTotalPoints() int32 {
	if x != nil {
		return x.TotalPoints
	}
	return 0
}

var File_rpc_get_membership_by_barcode_proto protoreflect.FileDescriptor

var file_rpc_get_membership_by_barcode_proto_rawDesc = []byte{
	0x0a, 0x23, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x5f, 0x62, 0x79, 0x5f, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x39, 0x0a, 0x1d, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x79, 0x42, 0x61, 0x72, 0x63,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61,
	0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x72,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0xc2, 0x01, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x42, 0x79, 0x42, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x10, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x74, 0x63, 0x6f, 0x6e, 0x67, 0x31, 0x34,
	0x31, 0x31, 0x2f, 0x72, 0x61, 0x70, 0x69, 0x64, 0x2d, 0x6c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_get_membership_by_barcode_proto_rawDescOnce sync.Once
	file_rpc_get_membership_by_barcode_proto_rawDescData = file_rpc_get_membership_by_barcode_proto_rawDesc
)

func file_rpc_get_membership_by_barcode_proto_rawDescGZIP() []byte {
	file_rpc_get_membership_by_barcode_proto_rawDescOnce.Do(func() {
		file_rpc_get_membership_by_barcode_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_get_membership_by_barcode_proto_rawDescData)
	})
	return file_rpc_get_membership_by_barcode_proto_rawDescData
}

var file_rpc_get_membership_by_barcode_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_membership_by_barcode_proto_goTypes = []interface{}{
	(*GetMembershipByBarcodeRequest)(nil),  // 0: pb.GetMembershipByBarcodeRequest
	(*GetMembershipByBarcodeResponse)(nil), // 1: pb.GetMembershipByBarcodeResponse
}
var file_rpc_get_membership_by_barcode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_get_membership_by_barcode_proto_init() }
func file_rpc_get_membership_by_barcode_proto_init() {
	if File_rpc_get_membership_by_barcode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_get_membership_by_barcode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembershipByBarcodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_membership_by_barcode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMembershipByBarcodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_get_membership_by_barcode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_membership_by_barcode_proto_goTypes,
		DependencyIndexes: file_rpc_get_membership_by_barcode_proto_depIdxs,
		MessageInfos:      file_rpc_get_membership_by_barcode_proto_msgTypes,
	}.Build()
	File_rpc_get_membership_by_barcode_proto = out.File
	file_rpc_get_membership_by_barcode_proto_rawDesc = nil
	file_rpc_get_membership_by_barcode_proto_goTypes = nil
	file_rpc_get_membership_by_barcode_proto_depIdxs = nil
}
